### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [liamstevens111/django-google-search-data-viewer#7]
Hello Alex 👋 , thank you for your effort on the code submission. This is Olivier, CTO at Nimble, and I am happy to be the reviewer for our code review session. Long, one of our Engineering Leads was the one you met in the first interview and he shared with me your scorecard already.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions/concerns and share your opinions about the implementation (if any) during the process.

If we’re aligned on any issue here and you’d like to correct them, please address the issue using proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. 😇

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding 🤘

**Comment by olivierobert** [comment]
I completed the first round of reviews. 

Note that I could successfully run the application in my local work environment thanks to the README 🙏 

However, the implementation is missing the most critical part: the background processing of the scraping of the search results page. The test coverage is also too low.

Regarding the scraping (using an HTML scraping library to get the HTML of the page), as a hint, the following workarounds are the most successful:
- Use rotating browser agents to appear as different "users".
- Throttle at random intervals the scraping jobs (each keyword scraping must be a different background job)

**Comment by liamstevens111** [comment]
Thanks Olivier.

Yes, I am addressing your issues as we speak and will reply according to the current issue I am working on.

Thank you for the hint; I did research this and as stated in the e-mail to Wansiri that I thought about the idea of changing the HTTP Headers and adding an artificial time delay for each keyword but from similar answers on StackOverflow I thought this would still be blocked by Google due to their perhaps advanced methods of detecting automated searches (not to mention same IP and cookies). I will look into this again after addressing your other issues.

Thank you

**Comment by liamstevens111** [comment]
Coming back to the Google scraping and background processing; if you would like I could attempt to implement this if you do not have any other issues you would like to attend to.

edit: thank you for the review so far, I enjoyed taking your feedback and applying the changes, especially relating to the scraping at the keyword level and the benefits it provides :thumbsup:

**Comment by olivierobert** [comment]
Thank you for proposing to working on the last issue. However, your efforts and feedback are sufficient at this stage. We aim to keep the application process as short as possible 🙏
