### ISSUE TITLE
Incorrect handling of CSV files

### ISSUE THREAD

**Issue by olivierobert** [liamstevens111/django-google-search-data-viewer#9]
## Issue

Uploading CSV files with different formats will result in different keywords being created.

### Format 1

```
keyword_1, keyword_2, keyword_3
```

One keyword will be created with the text "keyword_1, keyword_2, keyword_3"

### Format 2

```
keyword_1
keyword_2
keyword_3
```

Three keywords will be created: "keyword_1", "keyword_2", "keyword_3".

Here is an example:

![image](https://user-images.githubusercontent.com/696529/161217842-e0316ba9-ec23-4066-87f1-eb9b9465dfd0.png)

## Expected

The CSV upload form should yield an error when an incorrect CSV format is used. In addition, there should be instructions for the user to know how to prepare the correct upload data.

## Steps to reproduce

1. Go to http://127.0.0.1:8000/keywords/upload
2. Upload once a file with format #2 and another time with format #3
3. Go to http://127.0.0.1:8000/keywords/ to see the list of created keywords.

**Comment by liamstevens111** [comment]
I have now changed this to only parse the first "column" and throw an error if it detects multiple. To include actual commas in the search keyword it would need to be surrounded in double quotation marks to be valid.

I have re-factored the keyword parsing and moved it outside of the view / controller function to allow it to be tested separately on files without the request / response cycle being involved. I have also changed from the "view function" to a "class-based view" to re-use functionality in Django for displaying the form depending on if the request was a GET or POST.

Changed template page to emphasis only uploading keywords in the first column.

Pull request can be found [here](https://github.com/liamstevens111/google-search-data-viewer/pull/17) :ok_hand:

**Comment by olivierobert** [comment]
`KeywordFileUploadView` does have less responsibilities so it is indeed a great improvement. 

In terms of naming and code organization, I am not sure if `utils` is a good solution. `util` files tend to become baskets of unrelated things over time 😅 However, that will suffice for the purpose of this code challenge.
